### ISSUE TITLE
NullReferenceException in v0.9.35

### ISSUE THREAD

**Issue by kruncher** [playgameservices/play-games-plugin-for-unity#1433]
Since updating to the latest version of 'play-games-plugin-for-unity' I am now seeing the following exception appear in the Unity console window upon entering play mode (project in 'Android' mode).

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Editor.get_referenceTargetIndex () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:131)
UnityEditor.AssetImporterInspector.get_referenceTargetIndex () (at C:/buildslave/unity/build/Editor/Mono/ImportSettings/AssetImporterInspector.cs:26)
UnityEditor.Editor.get_target () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:121)
UnityEditor.AssetImporterInspector.OnDisable () (at C:/buildslave/unity/build/Editor/Mono/ImportSettings/AssetImporterInspector.cs:80)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:110)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
```

**Comment by claywilkinson** [comment]
Thanks for the feedback.  Which version of Unity are you using?  This looks like a bug in Unity vs. the plugin.

**Comment by kruncher** [comment]
I am using Unity 5.4.0p2 because the slightly more recent version of Unity is currently completely broken for my project due to other bugs.

**Comment by claywilkinson** [comment]
Thanks, I'll look into this.  In the mean time, if you can comment out the call to AssetDatabase.Refresh in GPGSUpgrader safely.

**Comment by claywilkinson** [comment]
Fixed in 0.9.36

**Comment by BaterieCZ** [comment]
not fixed in 36 :)

**Comment by keksmampfer** [comment]
yep still present in 36 + unity 5.6.1

**Comment by ematsuno** [comment]
I'm still getting this in 2017.41f1.  It is intermittent.  I reboot Unity.  It works for a play or two, but then it happens again...

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.InspectorWindow.OnSelectionChnge() (at C:buildslave/unity/build/Editor/mono/Inspector/InsprectorWindow.cs 147)

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.InspectorWindow.OnSelectionChange () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:147)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.OnSelectionChange () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:168)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:114)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
