### ISSUE TITLE
Service login problem. When published on market not login.

### ISSUE THREAD

**Issue by haydin20** [playgameservices/play-games-plugin-for-unity#1842]
Hi, 

My google play service is working good before publish game on Playstore.

I didnt understand anything. Everything working normally. But after publish, I m downlaoding on Playstore. This version not login service.

**Comment by GuillaumZ** [comment]
Hi, yes I've got the same problem here : 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1834

Perhaps you should try the "SHA1 trick" that worked for a lot of people here (see the post)
Please tell me if it's working for you (because it didn't work for me)

**Comment by haydin20** [comment]
Befor i had login problem. I solved with editting SHA1. i will try again now.

**Comment by haydin20** [comment]
i solved the problem. Its about with SHA1. 

Follow this steps. 

Go to your google play developer page. And find app singing on left side. 
and copy your SHA-1 on Application signing certificate not uploading certificate.
And go to https://console.developers.google.com 
and change finger print with this.

Not need upload new version of your application. When you edited you will show your application will login. 

Good luck !

**Comment by GuillaumZ** [comment]
YEAH !
Thank you, I just understood the same thing. 
I tried again when you wrotte that it had worked for you ... 
I was using the wrong SHA1 ....

![keystoresolution](https://user-images.githubusercontent.com/8102439/28427362-3a4352cc-6d76-11e7-8230-0c2b53028397.jpg)

**Comment by barozinugroho** [comment]
I had the same problem, I am confused with the solution that @GuillaumZ and @haydin20. because in my Google API account, I Already have the SHA-1 certificate fingerprint from both App Signing Certificate and Upload Certificate, but it still won't authenticate with the Play Games service.

I already linked my games with Client ID from Google API Credential, but it still won't authenticate.

I already upload my games in internal test track with Keystore that using SHA-1 Upload Certificate, is it internal test track can't access play games service ?

**Comment by barozinugroho** [comment]
I already solved this problem. the problem is I try to get ServerAuthCode and ID token from play games when I did not use Web ID Client from firebase google-service.json, instead I use Web ID client from linked app play games in the Unity > Window > Google Play Games > Setup > Android Setup > Web App Client ID > Client ID.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
