### ISSUE TITLE
GPGS crash when app open and ERROR_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by IgnatevSV** [playgameservices/play-games-plugin-for-unity#1947]
Using GPGS 0.9.41 and Unity 5.5.2f1 crashes after try to authenticate.
Also i created another test project with only 4 buttons("activate", "authenticate", "show_achievements", "show_leaderboards"), signed it, loaded in dev console, created services, created xml, etc...
No any reaction after:

PlayGamesPlatform.Activate();
And app crashes after:

Social.localUser.Authenticate((bool isSuccessful) => {Debug.log(isSuccessful)});
tolgau solution didn't help.
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604
Just don't know, what to do...

I recreated test app with GPGS 0.9.40. So, after the same actions app no more crashes, but it send me "ERROR_NOT_AUTHORIZED".
I double-checked SHA1 keys, Bundle ID, xml manifest, testers emails, enable test groups, apply testers invitations... But still can't login.

**Comment by YoloSwaggings720** [comment]
Did you use logcat when testing with 0.9.41 ? To use logcat, you have to go to this path: F:\Android\sdk\tools or wherever your android sdk is located. Then click on monitor and you will see the logs.

I got an error that said APP_ID not found or something and it crashed.  If you are having the same issue, then heres my [solution](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1935)

**Comment by mobeenk** [comment]
my game is crashing when I try to signin as well
I use unity 5.4 
 with plugin version 9.41
desperate for a solution for days !!!

**Comment by idurvesh** [comment]
Same here, it used to work in the previous version. Upgrading to latest one crashes app while authenticating

**Comment by IgnatevSV** [comment]
Well, after so many wasted days something started work...partially.
I installed 9.38 ver of GPGS, setted xml, keys, etc. After that i also UPLOADED actual version of app in console and release it(as closed alpha) and installed my app through tester invite and google play. So, now i can login, view leaderboards and achievements windows. BUT! Sometimes i also can't login and view this windows. Also in console, in testers reports i get 16(!!!) crash reports of "java.lang.Error" com.google.android.gms.common.internal.zzf$zza.zzb.
And after all...I can use GPGS only if i installed my app from google play. If i directly install my apk from my PC, i also can't login. I pretty sure, that there is no need in app release(at least i didn't notice that in variety of tutorials and requirements), but maybe i miss something. But this 16 crash reports haunt my mind now...

**Comment by mobeenk** [comment]
But if you release an alpha
How can you change the code later?
Each time you want to test you will release new alpha?

**Comment by IgnatevSV** [comment]
Yes, each time i want to test something in GPGS. Pretty convenient, huh?
If i reinstall it from PC, GPGS just won't login.

**Comment by sampenguin** [comment]
We are also seeing crashes somewhere after activating the plugin, versions 9.38 and 9.41, Unity 5.6.3p1. Like others have checked and double checked all the dependencies, reinstalled multiple times. Not getting anything really useful out of the logcat...

It does show Op: SIGN_IN status: VALID, and I can see the google username popup slide away just before crash, so this crash is happening after an authentication handshake.

Is anyone else with this problem using a Firebase link with their app? Curious if that might be a factor.

**Comment by sampenguin** [comment]
Just solved our crash issue. Apparently we had an incorrect leaderboardID in the APK (different than the ID listed in GP console). Once this was corrected, everything worked again. So double check all your achievement and leaderboard IDs are EXACTLY correct on both sides, no extra spaces, etc.

It would be great if there was maybe some nicer error messaging around that kind of situation rather than a crash with no logging. :)

**Comment by VusalJalilov** [comment]
**Using GPGS 0.9.41 and Unity 5.5.4p3 crashes after try to authenticate.**
Built the Minimal project from the samples.

Android version - 7.0
Samsung Note 5

Inside Android SDK Manager: 
Google Play Services - 44
Google Repository - 58
Android Support Repository - 47

**Comment by IgnatevSV** [comment]
Thanks for feedback. I test achievements unlock and I always get "Could not Unlock, no achievement with ID <and_here_is_my_achievement_id>". I tested it in 2 apps(GPGS 0.9.38), i checked this achievement ID string in services and my app many times, copy-paste it, try to use const string from generated GPSIDs script, but nothing is worked...
Also, anti-piracy is disabled, so i still don't understand why i need to install my app from GPS.

I'll try to use GPGS 0.9.36. The results will be reported later.

**Comment by IgnatevSV** [comment]
Well, in GPGS 0.9.36 correctly works authentication, leaderboards and achievements unlocking.

**Comment by AdnanNazir** [comment]
Hello Anyone can suggest? I am also having exactly same issue. Something to do with the plugin version? Which version should I use to get rid of that exception that causes app crash.

**Comment by xenonsin** [comment]
@IgnatevSV What version of Unity are you running? I think people who upgraded to Unity 5.5.4+ can't use GPGS 0.9.36 I believe.

**Comment by AdnanNazir** [comment]
I am on Unity 5.3 if you are asking me.

**Comment by IgnatevSV** [comment]
@xenonsin Unity 5.5.2f1 as I wrote at first message, but sorry for late answer anyway.

**Comment by amykishor** [comment]
@maxbackcontry You made my day. I was struggling with it for more than 24 hours. Now its working.

**Comment by aneeshpanoli** [comment]
if anyone has the same problem as I had, the solution is given here. [https://github.com/playgameservices/play-games-plugin-for-unity/issues/2013#issuecomment-385303507](url)

I t solved a lot of unrelated dunity crashes for me.

**Comment by Pseudoless** [comment]
@aneeshpanoli Thank you SO MUCH!
This worked like a charm for me, and I ended up modifying the template-AndroidManifest.txt file.
I replaced "\ " by "\u003" directly in the template file, so I wouldn't have to update my manifest file everytime I have to add new resources and do the Setup thing.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
