### ISSUE TITLE
Crash after “Application ID ( 232323232323) must be a numeric value.”

### ISSUE THREAD

**Issue by qbit86** [playgameservices/play-games-plugin-for-unity#2013]
When I export to Gradle project and build APK in Android Studio, I get this error in run time and then application crashes:
```
E/ValidateServiceOp(7463): Application ID ( 232323232323) must be a numeric value. Please verify that your manifest refers to the correct project ID.
D/AndroidRuntime(8305): Shutting down VM
V/AlarmManager(2657): waitForAlarm result :8
E/AndroidRuntime(8305): Caused by: java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
E/AndroidRuntime(8305): 	at com.google.android.gms.common.internal.zze$zza.zzc(Unknown Source)
E/AndroidRuntime(8305): 	at com.google.android.gms.common.internal.zze$zza.zzv(Unknown Source)
E/AndroidRuntime(8305): 	at com.google.android.gms.common.internal.zze$zze.zzauc(Unknown Source)
E/AndroidRuntime(8305): 	at com.google.android.gms.common.internal.zze$zzd.handleMessage(Unknown Source)
E/AndroidRuntime(8305): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(8305): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(8305): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
E/AndroidRuntime(8305): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(8305): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(8305): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(8305): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
Looks like the problem is in leading space in app id. But this space in AndroidManifest is intentionally added via template XML:
```
<!-- the space in these forces it to be interpreted as a string vs. int -->
<meta-data android:name="com.google.android.gms.games.APP_ID"
    android:value="\ 232323232323" />
```

This does not happen when I build via Gradle directly without exporting; or if I use internal legacy build system.

Plugin: 0.9.36, Unity: 2017.2.0f2

**Comment by ettore3091** [comment]
I'm having the same issue, did you manage to solve it?

**Comment by khaledElshimy** [comment]
replace "\ " with "\u003

for example
before:
<meta-data android:name="com.google.android.gms.games.APP_ID"
    android:value="\ 232323232323" />

after:
<meta-data android:name="com.google.android.gms.games.APP_ID"
    android:value="\u003232323232323" />

**Comment by jyrkive** [comment]
Thanks @khaledElshimy, your workaround helped in my project. 👍

**Comment by hazarartuner** [comment]
Thank you @khaledElshimy it worked for me too 👍 🎉   When I updated the Unity version to 2018.2, this bug occurred. if there are anybody having the same issue, you should find the AndroidManifest.xml in your project and do what @khaledElshimy says to do 😄

**Comment by jyrkive** [comment]
Yeah, updating to Unity 2018.2 was the trigger for us as well. The other development branch which uses Unity 2018.1 is still unaffected.

**Comment by exzizt** [comment]
@hazarartuner Your solution worked for me as well. However, which "AndroidManifest.xml" file needed to be changed exactly? I found a lot of those "AndroidManifest.xml" files in my project. I changed one or two and it didn't work. Then, I finally searched and changed every single one I could find and it worked.

**Comment by alkubo** [comment]
@exzizt , i think it's  the GooglePlayGame AndroidManifest.xml, which is in "Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/"  folder

**Comment by Jbrandan** [comment]
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003232323232323" />  
I did not work Unity 2018.2.0f2 (64-bit)  plugin 0.9.50

**Comment by alphadogware** [comment]
The AndroidManifest.xml file is recreated on build, so why would changing the value in that file make any difference?  i tried this anyway and it didn't work for me, the file got overwritten when I built again for android.

**Comment by ChristianTellefsen** [comment]
You can update the template file that generates the manifest.

`Assets\GooglePlayGames\Editor\template-AndroidManifest.txt`

**Comment by alphadogware** [comment]
I just tried updating the template file and still got the same error.

**Comment by khaledElshimy** [comment]
You can export android studio project with gradle, then you will find
googleplaygames folder where androidmanifest.xml exist.

**Comment by alphadogware** [comment]
Just so I get this straight, you are saying that each time I build for android I'm going to have to build, manually make the change,  then pull up the project in android studio and rebuild an apk?

**Comment by wbsaputra** [comment]
replace "\ " with "\u003

before:
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 232323232323" />
after:
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003232323232323" />

Unity 2018.2.0f2 (64-bit) Mac - GooglePlayGamesPlugin-0.9.50
Yes it worked, you saved my life

**Comment by ChristianTellefsen** [comment]
I changed both the template file, and the generated AndroidManifest.xml. The error immediately disappeared. I am building the .apk directly from Unity / gradle (not exporting to Android Studio).

**Comment by alphadogware** [comment]
I change the file GooglePlayGames\Editor\template-AndroidManifest.txt

from 

        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\ __APP_ID__" />
to 

        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\u003__APP_ID__" />

No effect no the AndroidManifest.xml that is generated each time I build from Unity that is located in /Temp/gradleOut/build/intermediates/manifests/full/release.

I am working on a Mac, so ChristianFellefsen, please tell me which template file you edited.

**Comment by alphadogware** [comment]
Also, I have searched for APP_ID and manifest in my project folder and editing any of those files has no effect on the AndroidManifest.xml that is generated.

**Comment by EvgenyMelnikov** [comment]
@alphadogware, make changes only in GooglePlayGames\Editor\template-AndroidManifest.txt. Than regenerate manifest at Window->GooglePlayGames->Setup->AndroidSetup->Setup.

**Comment by conyard** [comment]
the project has two andriodmanifest.xml,you must modify the anther one




| |
龚阳辉
邮箱：gongyanghui1986@163.com
|

签名由 网易邮箱大师 定制

On 08/13/2018 20:42, EvgenyMelnikov wrote:

@alphadogware, make changes only in GooglePlayGames\Editor\template-AndroidManifest.txt. Than regenerate manifest at Window->GooglePlayGames->Setup->AndroidSetup->Setup.

**Comment by alphadogware** [comment]
HOLY CRAP!!!  I fixed it!

Put the u300 -before- the slash, not after it.

        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="u003\__APP_ID__" />

**Comment by exzizt** [comment]
Can a patch please be written for this? I think it's fair enough to say that this has been going on long enough. Honestly, where'd all the support go for this plugin?

**Comment by Thaina** [comment]
days of frustration and just found this. It's work. But why this not got fixed yet...

**Comment by dodiayar** [comment]
Thanks @EvgenyMelnikov

**Comment by hippogamesunity** [comment]
OMG

**Comment by hippogamesunity** [comment]
Can confirt this work:
- open template-AndroidManifest.txt
- "\ __APP_ID__" to "\u003__APP_ID__" />
- setup GPGS from Unity (press Window/Google Play Services/Setup)

**Comment by CremaLuca** [comment]
Unity 2018.2.6f1, replacing "\__APP_ID__" with "\u003__APP_ID__" worked for me.

Lost a whole day to figure this out.

**Comment by mhamedali** [comment]
Thanks, replacing "_APP_ID_" with "\u003__APP_ID__" in template-AndroidManifest.txt , worked for me

**Comment by Spyispie120** [comment]
Took me 2 days. Thank you alot!  
Also, remember that it is "\u003..." and not "\ u003...". I was under the impression that space doesn't matter.
Unity 2018.2.6f1 👍

**Comment by qbit86** [comment]
What does `\u003` actually mean in this context? Looks like some Unicode code point or something like that. But it's not clear who exactly is responsible for interpreting this escaped/encoded thing; which part of pipeline?

**Comment by jyrkive** [comment]
In ASCII, 0x03 is the ETX control character ("end of text"). I have no idea what significance it has for the Android build process.

**Comment by dongprojectteam** [comment]
Awesome!!!!!!!!!!!!!!!!!! 
Thank you EvgenyMelnikov !!
You saved my life!

**Comment by iPaulPro** [comment]
Unreal that this issue is still open after almost a year. So much time lost to this bug.

**Comment by totespare** [comment]
My god, days after this problem and it was this stupid shit...

Thanks for solving it!

**Comment by 3DGamesDeveloper** [comment]
Solution. Summary: 
- Go to GooglePlayGames\Editor\template-AndroidManifest.txt
- Open template-AndroidManifest.txt.
-Change "\ APP_ID" to "\u003__APP_ID__"
-setup GPGS from Unity (press Window/Google Play Services/Setup). Then regenerate manifest at Window->GooglePlayGames->Setup->AndroidSetup->Setup.
I want to express my sincere gratitude to each and every one of you who helped to solve this issue. Thank you!

**Comment by v01pe** [comment]
> What does `\u003` actually mean in this context? Looks like some Unicode code point or something like that.

I was curious as well and did a little research… when you look at a unicode table you can see, that the characters with the code `\u003X` where X is any number [0-9] are actually the numbers 0 to 9. So whatever number comes after the 3 defines the unicode for that number. What comes out is the first number of the APP ID in unicode, followed by the rest of the numbers.

So this is not really a fix, but a clever hack/ workaround to trick the system to do the right thing. No idea why the `\ ` is there in the first place, because clearly it should just resolve to the APP ID number in the end.

**Comment by tejaskohli1992** [comment]
Hi, tried making the following change in the template-AndroidManifest.txt file
"\ APP_ID" to "\u003__APP_ID__"
However the leaderboard is still crashing on saving the score, Can anyone please suggest how to resolve this issue.
Working on unity version 2018.1.8f and GPGS version 0.95.
Thanks.

**Comment by UnLeving** [comment]
> Hi, tried making the following change in the template-AndroidManifest.txt file
> "\ APP_ID" to "\u003__APP_ID__"

It's not necesary to add u003. You need just remove whitespace in template.
android:value="\ __APP_ID__" />
android:value="\__APP_ID__" />
after that you need to rebuild manifest (window -> google play games -> setup-> android setup).
OR go to generated manifest %\Assets\GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.plugin\AndroidManifest.xml 
and remove whitespace as well.

**Comment by tejaskohli1992** [comment]
> > Hi, tried making the following change in the template-AndroidManifest.txt file
> > "\ APP_ID" to "\u003__APP_ID__"
> 
> It's not necesary to add u003. You need just remove whitespace in template.
> `android:value="\[whitespace]__APP_ID__" />`
> `android:value="\__APP_ID__" />`
> after that you need to rebuild manifest (window -> google play games -> setup-> android setup).
> OR go to generated manifest %\Assets\GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.plugin\AndroidManifest.xml
> and remove whitespace as well.

Hi, tried making the following changes, however now the signIn functionality has stopped working, hence unable to access leaderboard.

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52.

**Comment by acoppes** [comment]
Are you going to release version 0.9.52? can't find it in [releases](https://github.com/playgameservices/play-games-plugin-for-unity/releases)

**Comment by olehkuznetsov** [comment]
Thanks for noticing will update the releases.
You can get latest version 0.9.57 in the [current-build folder](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build).

**Comment by kiranachar992** [comment]
> replace "\ " with "\u003
> 
> before:
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 232323232323" /> `
> after:
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003232323232323" />`

Not worked for me. Still getting same issue.

**Comment by JordiGN** [comment]
My android manifest already has the "\u003" but still not working, it's crashing when using "PlayGamesPlatform.Activate()"

Unity: 2017.4.15f1
com.google.android.gms.games.unityVersion: 0.9.62
DeltaDNA SDK: deltadna-sdk-v4.12.3
GoogleMobileAds: v3.16

**Comment by charleswowiemoreno** [comment]
> replace "\ " with "\u003
> 
> before:
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 232323232323" /> `
> after:
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u003232323232323" />`

Wow, this worked for me. Thanks man!
