### ISSUE TITLE
Play service not signing in and leaderboard and achievement is not working with Unity 

### ISSUE THREAD

**Issue by shohan4556** [playgameservices/play-games-plugin-for-unity#2332]
I have installed properly google play service and followed the instruction but after publishing on playstore I am unable to signin play service and leaderboard and achievement also not working. please help me. 

```
using UnityEngine;
using System.Collections;
using UnityEngine.SceneManagement;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class SplashScreenScript : MonoBehaviour {

    //public float autoLoadNextLevelAfter;

    void Start()
	{
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().RequestEmail().Build();
		PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;
		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate();

		ActivateSignIn();

       // Invoke("LoadNextLevel", autoLoadNextLevelAfter);
    }

	public void ActivateSignIn()
	{
		Social.localUser.Authenticate((bool success) => {
			if (success)
			{
				print("successfully logged in");
			}
			else
			{
				print("Something... wrong on login");
			}
		});
	}

    public void LoadNextLevel() {
        SceneManager.LoadScene("MainScene_Gameplay");
    }

}



```

**Comment by olehkuznetsov** [comment]
It seems you need to add additional linked app for release version in Google Play Console.

**Comment by shohan4556** [comment]
> It seems you need to add additional linked app for release version in Google Play Console.

I have published the game on playstore. please tell me how to link my game to google play console.

**Comment by shohan4556** [comment]
Already linked up my apps

**Comment by Mikecoon** [comment]
This plugin is broken.

Repo seems to be abandoned.

Any alternatives?

**Comment by Mikecoon** [comment]
Okay, I see developer pulled some requests, 
Really hope for solution for that problem.

Currently, there are no free public solutions for Unity 2018.2 + Google Play Services.

**Comment by nikoskon2003** [comment]
I had the same problem with the authenticatiin crashing the game, and i fixed it with #2013 .
But still i cant sign in when i run the game from my phone!
Ps. Google play services were working on an earlier release before updating to unity 2018.2, so the new version of unity must have caused problems!

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52.

**Comment by olehkuznetsov** [comment]
Can you check if logcat provides some meaningful information during auth process, please?

**Comment by Mikecoon** [comment]
Auth works great now, thanks!

**Comment by olehkuznetsov** [comment]
Most common sign-in error reason is lack of linked package+SHA1 combination in Play Google Console.
Also check if you have account you use for sign-in in testers list in Play Google Console, so, you can sign-in to unpublished app.

**Comment by h0per1** [comment]
I still get crash on phone with 0.9.52 and unity 2018.2.13f1 what is the problem plz help me

**Comment by shohan4556** [comment]
I am still having the problem

**Comment by nikoskon2003** [comment]
Update and redo th setup process

**Comment by nikoskon2003** [comment]
But im also having the problem that it doesn't sign-in

**Comment by olehkuznetsov** [comment]
Can you show logcat during sign-in attempt, please?

**Comment by stabak** [comment]
Hi, I have a problem authenticating.
I have installed the latest google play plugin version (0.9.52).
Authentication window is killed abruptly with error code 13 (when authenticate request is made right after app starts), or 16 (when the request is repeated after its failed the first time).

Please see the logcat:
11-01 15:27:29.083 19603-23234/? I/EventLogSendingHelper: Sending log events.
11-01 15:27:31.009 2121-10609/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.tabak.rots/com.unity3d.player.UnityPlayerActivity (has extras)} from uid 10034 on display 0
11-01 15:27:31.021 2121-2143/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10034)
11-01 15:27:31.027 2121-2143/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10034)
11-01 15:27:31.043 2121-2840/? I/ActivityManager: Start proc 23837:com.tabak.rots/u0a212 for activity com.tabak.rots/com.unity3d.player.UnityPlayerActivity
11-01 15:27:31.050 23837-23837/? I/art: Late-enabling -Xcheck:jni
11-01 15:27:31.142 19603-23501/? I/DeviceStateChecker: DeviceStateChecker cancelled
11-01 15:27:31.144 19603-19603/? I/MicroDetector: Keeping mic open: false
11-01 15:27:31.145 19603-23238/? I/AudioController: internalShutdown
11-01 15:27:31.146 19603-23813/? I/MicroRecognitionRunner: Stopping hotword detection.
11-01 15:27:31.188 1748-23831/? D/audio_hw_primary: disable_audio_route: usecase(8) reset and update mixer path: audio-record
11-01 15:27:31.189 1748-23831/? D/audio_hw_primary: disable_snd_device: snd_device(63: voice-rec-mic)
11-01 15:27:31.197 1748-2007/? I/SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0
11-01 15:27:31.199 19603-23238/? I/MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
11-01 15:27:31.200 19603-23240/? I/MicroRecognitionRunner: Detection finished
11-01 15:27:31.314 2121-2164/? I/ActivityManager: Displayed com.tabak.rots/com.unity3d.player.UnityPlayerActivity: +285ms
11-01 15:27:31.347 23837-23851/? I/Unity: SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 4, Memory = 2970mb
11-01 15:27:31.348 23837-23851/? I/Unity: SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf), 0 little (mask: 0x0)
11-01 15:27:31.348 23837-23851/? I/Unity: ApplicationInfo com.tabak.rots version 0.1 build d1eb2a15-49e6-4cc6-82a6-f9bee52f72df
11-01 15:27:31.348 23837-23851/? I/Unity: Built from '2018.2/release' branch, Version '2018.2.6f1 (c591d9a97a0b)', Build type 'Release', Scripting Backend 'mono'
11-01 15:27:31.549 23837-23851/? I/Adreno: QUALCOMM build                   : a5b4970, If5818605d9
                                           Build Date                       : 10/12/16
                                           OpenGL ES Shader Compiler Version: XE031.09.00.04
                                           Local Branch                     : N24D
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
11-01 15:27:31.593 23837-23851/? D/Unity:  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_d
11-01 15:27:31.593 23837-23851/? D/Unity: raw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params
11-01 15:27:31.643 23837-23851/? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
11-01 15:27:31.643 23837-23851/? W/AudioTrack: notificationFrames=-21 clamped to the range -1 to -8
11-01 15:27:31.645 1748-2639/? W/AudioFlinger: createTrack_l(): mismatch between requested flags (00000104) and output flags (00000006)
11-01 15:27:31.647 23837-23851/? D/AudioTrack: Client defaulted notificationFrames to 192 for frameCount 1536
11-01 15:27:31.648 1748-6694/? W/AudioFlinger: checkEffectCompatibility_l(): non HW effect Mot Speaker Helper: Music on playback thread in fast mode
11-01 15:27:31.649 1748-6694/? E/AudioEffect: set(): AudioFlinger could not create effect, status: -22
11-01 15:27:31.649 1748-6694/? E/AudioPolicyEffects: addOutputSessionEffects(): failed to create Fx  music_helper on session 1337
11-01 15:27:31.649 1748-1929/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
11-01 15:27:31.652 1748-1929/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
11-01 15:27:31.684 19603-19603/? I/PBSessionCacheImpl: Deleted sessionId[47844166631074] from persistence.
11-01 15:27:31.716 19603-19603/? W/SearchServiceCore: Abort, client detached.
11-01 15:27:31.726 19603-19603/? I/StreamController: cleanUpControllerScope(nowcards-15-14fe4613-8add)
11-01 15:27:32.195 23837-23851/? V/MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
11-01 15:27:32.199 23837-23851/? V/MediaRouter: Updating audio routes: AudioRoutesInfo{ type=SPEAKER }
11-01 15:27:32.202 23837-23851/? V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
11-01 15:27:34.124 19603-23240/? I/EventLogSendingHelper: Sending log events.
11-01 15:27:34.142 19603-19603/? I/WorkerManager: dispose()
11-01 15:27:34.219 19603-23611/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::h, WorkerId=context, id=52acf46}
11-01 15:27:34.223 19603-23611/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::j, WorkerId=context, id=485c507}
11-01 15:27:34.252 19603-23611/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::k, WorkerId=context, id=3ae1c5d}
11-01 15:27:34.252 19603-23611/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::i, WorkerId=context, id=ab499d2}
11-01 15:27:34.252 19603-23611/? I/WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::m, WorkerId=context, id=2faaa3}
11-01 15:27:34.380 2121-12724/? W/SensorService: sensor 00000000 already enabled in connection 0xac188cc0 (ignoring)
11-01 15:27:34.414 12078-23821/? I/Places: ?: PlacesBleScanner stop()
11-01 15:27:34.414 12078-12078/? I/BeaconBle: Scan canceled successfully.
11-01 15:27:34.425 12078-23821/? I/PlaceInferenceEngine: [anon] Changed inference mode: 0
11-01 15:27:34.439 23837-23862/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-01 15:27:34.456 12078-12078/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=null]
11-01 15:27:34.473 23837-23851/? I/Unity: Starting Auth with token client.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.554 23837-23851/? W/Unity: !!! [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 WARNING: Creating new PlayGamesPlatform
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.555 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: Activating PlayGamesPlatform.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.555 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.555 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: Creating platform-specific Play Games client.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.555 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: Creating Android IPlayGamesClient Client
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.613 23837-23851/? D/TokenFragment: Creating fragment
11-01 15:27:34.614 23837-23837/? D/TokenFragment: onStart()
11-01 15:27:34.614 23837-23837/? D/TokenFragment: onResume called
11-01 15:27:34.614 23837-23837/? D/TokenFragment: Building client for: de521a0 (a:false e:true i:false wc: 1057935321168-lek8f11elrn8fj7lanoug1gp598ckkn0.apps.googleusercontent.com f: false)
11-01 15:27:34.628 23837-23851/? I/Unity: ---- [0] -- 1048613
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.633 23837-23837/? W/PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
11-01 15:27:34.661 23837-23837/? D/TokenFragment: No connected Games API
11-01 15:27:34.661 23837-23837/? E/TokenFragment: Setting result error code to: 13
11-01 15:27:34.692 23837-23837/? D/TokenPendingResult:  Calling onResult for callback: GooglePlayGames.Android.TokenResultCallback result: Status: Status{statusCode=ERROR, resolution=null} email: <null> id:<null> access: <null>
11-01 15:27:34.748 23837-23837/? D/GamesUnitySDK: Performing Android initialization of the GPG SDK
11-01 15:27:34.798 23837-23837/? I/Unity: Building GPG services, implicitly attempts silent auth
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.801 23837-23837/? I/GamesNativeSDK: Using existing jar.
11-01 15:27:34.801 23837-23837/? I/GamesNativeSDK: Writing 1941 bytes to jar file
11-01 15:27:34.810 23837-23837/? I/GamesNativeSDK: Using existing jar.
11-01 15:27:34.810 23837-23837/? I/GamesNativeSDK: Writing 1066 bytes to jar file
11-01 15:27:34.821 23837-23837/? W/PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
11-01 15:27:34.822 23837-23902/? I/GamesNativeSDK: Auth operation started: SIGN IN
11-01 15:27:34.822 23837-23902/? I/GamesNativeSDK: Connecting to Google Play...
11-01 15:27:34.949 23837-23837/? D/TokenFragment: Done with processRequest, result is pending.
11-01 15:27:34.954 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 13
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.954 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.955 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:34 +01:00 DEBUG: there are pending auth callbacks - starting AuthUI
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:34.958 19821-19834/? W/GamesServiceBroker: Client connected with SDK 12451000, Services 14366015, and Games 74660030
11-01 15:27:34.974 19821-19908/? W/GamesServiceBroker: Client connected with SDK 12451000, Services 14366015, and Games 74660030
11-01 15:27:34.985 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.005 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.011 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.037 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.045 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.216 2121-2131/? I/art: Background partial concurrent mark sweep GC freed 31695(1664KB) AllocSpace objects, 1(20KB) LOS objects, 33% free, 25MB/38MB, paused 1.622ms total 122.155ms
11-01 15:27:35.233 23837-23837/? V/GamesNativeSDK: Play Games callback indicates connection failure.
11-01 15:27:35.236 23837-23902/? I/GamesNativeSDK: UI interaction required to connect to Google Play.
11-01 15:27:35.236 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.239 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.254 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:35 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:35.254 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:35 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:35.258 23837-23851/? I/Unity: 1 auth success:  False
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:35.260 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.270 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.272 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.273 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:35 +01:00 DEBUG: Invoking user callback on game thread
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:35.291 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.293 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.480 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:35.495 23837-23837/? I/TokenFragment: onConnected called
11-01 15:27:35.496 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:36.806 2121-2146/? E/BatteryStatsService: no controller energy info supplied
11-01 15:27:36.839 22137-22137/? D/StateMachine: EVENT: ACTIVATE
11-01 15:27:36.839 22137-22137/? D/StateMachine: invalid transition, current state: ACTIVE
11-01 15:27:36.877 2121-2146/? E/BatteryStatsService: power: Missing API
11-01 15:27:36.900 2121-2146/? E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
11-01 15:27:40.238 23837-23902/? V/GamesNativeSDK: Detaching from JVM on thread main_dispatch
11-01 15:27:44.176 23837-23851/? I/Unity: Starting Auth with token client.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:44.178 23837-23851/? D/TokenFragment: Fragment exists.. calling processRequests
11-01 15:27:44.179 23837-23851/? D/TokenFragment: Building client for: 2a2d7df (a:false e:true i:false wc: 1057935321168-lek8f11elrn8fj7lanoug1gp598ckkn0.apps.googleusercontent.com f: false)
11-01 15:27:44.180 23837-23851/? W/PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
11-01 15:27:44.198 23837-23851/? D/TokenFragment: Done with processRequest, result is pending.
11-01 15:27:44.200 23837-23851/? I/Unity: ---- [0] -- 2097177
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:44.221 19821-19913/? W/GamesServiceBroker: Client connected with SDK 12451000, Services 14366015, and Games 74660030
11-01 15:27:44.245 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.262 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.277 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.302 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.314 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.465 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.471 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.488 23837-23837/? I/TokenFragment: onConnected called
11-01 15:27:44.558 19821-19931/? W/GamesServiceBroker: Client connected with SDK 14366000, Services 14366015, and Games 74660030
11-01 15:27:44.570 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.579 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.594 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.615 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.616 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.773 2121-4659/? I/ActivityManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.tabak.rots cmp=com.tabak.rots/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10212 on display 0
11-01 15:27:44.790 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.790 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.844 2121-12046/? I/ActivityManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms cmp=com.google.android.gms/.auth.api.signin.ui.SignInActivity (has extras)} from uid 10212 on display 0
11-01 15:27:44.897 23837-23925/? I/OpenGLRenderer: Initialized EGL, version 1.4
11-01 15:27:44.897 23837-23925/? D/OpenGLRenderer: Swap behavior 1
11-01 15:27:44.938 19821-19881/? W/GamesServiceBroker: Client connected with SDK 14366000, Services 14366015, and Games 74660030
11-01 15:27:44.955 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.965 2121-2164/? I/ActivityManager: Displayed com.google.android.gms/.auth.api.signin.ui.SignInActivity: +89ms (total +138ms)
11-01 15:27:44.969 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:44.985 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.013 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.025 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.158 19821-19937/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.159 19821-19935/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.167 2121-12724/? I/ActivityManager: START u0 {cmp=com.google.android.gms/.common.api.GoogleApiActivity (has extras)} from uid 10014 on display 0
11-01 15:27:45.222 2121-10609/? I/ActivityManager: START u0 {act=com.google.android.gms.games.SIGN_IN flg=0x4000000 pkg=com.google.android.play.games cmp=com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity (has extras)} from uid 10014 on display 0
11-01 15:27:45.302 22786-22786/? I/AppLifecycleTracker: onActivityCreated: 
11-01 15:27:45.339 22786-22786/? I/AppLifecycleTracker: onActivityStarted: 
11-01 15:27:45.349 22786-22786/? I/AppLifecycleTracker: onActivityResumed: 
11-01 15:27:45.354 22786-22786/? I/SignInActivity: Transition from -1 to 0
11-01 15:27:45.396 31661-31701/? I/CarrierServices: [2369] bwa.a: FiST: Wifi connectivity status true
11-01 15:27:45.408 31661-31739/? I/CarrierServices: [2388] czn.a: CarrierServices.apk is not sim call manager. Not enabling MMTel.
11-01 15:27:45.408 31661-31739/? I/CarrierServices: [2388] bcs.run: (MMTel): : Ignoring Network Change based on IMS preferences
11-01 15:27:45.410 31661-31701/? I/CarrierServices: [2369] bwf.d: Connected state: [1], networkType: [WIFI]
11-01 15:27:45.562 19821-19835/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:45.589 2121-2164/? I/ActivityManager: Displayed com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity: +321ms (total +406ms)
11-01 15:27:47.982 1748-1929/? D/audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
11-01 15:27:47.986 1748-1929/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-01 15:27:48.455 31661-31701/? I/CarrierServices: [2369] bwa.a: FiST: Wifi connectivity status true
11-01 15:27:48.462 31661-31739/? I/CarrierServices: [2388] czn.a: CarrierServices.apk is not sim call manager. Not enabling MMTel.
11-01 15:27:48.463 31661-31739/? I/CarrierServices: [2388] bcs.run: (MMTel): : Ignoring Network Change based on IMS preferences
11-01 15:27:48.465 31661-31701/? I/CarrierServices: [2369] bwf.d: Connected state: [1], networkType: [WIFI]
11-01 15:27:48.643 17027-17048/? I/Finsky: [2993] com.google.android.finsky.bn.an.run(6): Stats for Executor: BlockingExecutor com.google.android.finsky.bn.ao@4089a53[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 7]
11-01 15:27:48.647 17027-17048/? I/Finsky: [2993] com.google.android.finsky.bn.an.run(6): Stats for Executor: LightweightExecutor com.google.android.finsky.bn.ao@5e12f90[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 44]
11-01 15:27:49.069 17027-17048/? I/Finsky: [2993] com.google.android.finsky.bn.an.run(6): Stats for Executor: bgExecutor com.google.android.finsky.bn.ao@6bf5089[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 33]
11-01 15:27:49.087 22786-22786/? E/ViewRootImpl[SignInActivity]: Attempting to destroy the window while drawing!
                                                                   window=android.view.ViewRootImpl@3f13bb9, title=com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity
11-01 15:27:49.150 22786-22786/? I/SignInActivity: Transition from 0 to 1
11-01 15:27:49.184 22786-22786/? I/SignInActivity: Transition from 1 to 3
11-01 15:27:49.219 19821-19835/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:49.220 19821-19913/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:49.244 22786-22786/? I/SignInActivity: Transition from 3 to 4
11-01 15:27:49.274 12078-12078/? W/ChimeraUtils: Non Chimera context
11-01 15:27:49.287 19821-19908/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:49.403 17027-17048/? I/Finsky: [2993] com.google.android.finsky.bn.an.run(6): Stats for Executor: StorageAwareDownloadServiceManagerSpaceChecker com.google.android.finsky.bn.ao@cf5388e[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
11-01 15:27:49.437 19821-19890/? W/Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
11-01 15:27:49.437 19821-19890/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@14366015@14.3.66 (040300-213742215):2)
11-01 15:27:49.437 19821-19890/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@14366015@14.3.66 (040300-213742215):2)
11-01 15:27:49.620 19821-19890/? W/Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
11-01 15:27:49.620 19821-19890/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@14366015@14.3.66 (040300-213742215):2)
11-01 15:27:49.620 19821-19890/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@14366015@14.3.66 (040300-213742215):2)
11-01 15:27:49.978 22786-22786/? I/SignInActivity: Transition from 4 to 5
11-01 15:27:50.001 22786-22786/? I/SignInActivity: Transition from 5 to 6
11-01 15:27:50.031 19821-19834/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:50.039 19821-19835/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:50.210 22786-22786/? I/SignInActivity: Transition from 6 to 11
11-01 15:27:50.210 22786-22786/? W/SignInActivity: onSignInFailed()...
11-01 15:27:50.210 22786-22786/? W/SignInActivity: Sign in failed during 6
11-01 15:27:50.210 22786-22786/? W/SignInActivity: ==> Returning non-OK result: 10002
11-01 15:27:50.225 22786-22786/? I/AppLifecycleTracker: onActivityPaused: 
11-01 15:27:50.293 19821-19834/? W/GamesServiceBroker: Client connected with SDK 14768000, Services 14366015, and Games 74660030
11-01 15:27:50.358 22758-22758/? W/AutoManageHelper: Unresolved error while connecting client. Stopping auto-manage.
11-01 15:27:50.502 2121-2771/? W/InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@d597ac (uid=10014 pid=22758)
11-01 15:27:50.564 23837-23837/? E/TokenFragment: Setting result error code to: 16
11-01 15:27:50.567 23837-23837/? D/TokenPendingResult:  Calling onResult for callback: GooglePlayGames.Android.TokenResultCallback result: Status: Status{statusCode=CANCELED, resolution=null} email:  id: access: 
11-01 15:27:50.571 23837-23837/? V/GamesNativeSDK: Received Activity Resume Event.
11-01 15:27:50.573 23837-23837/? D/TokenFragment: onResume called
11-01 15:27:50.658 1748-6694/? W/AudioFlinger: checkEffectCompatibility_l(): non HW effect Mot Speaker Helper: Music on playback thread in fast mode
11-01 15:27:50.658 1748-6694/? E/AudioEffect: set(): AudioFlinger could not create effect, status: -22
11-01 15:27:50.658 1748-6694/? E/AudioPolicyEffects: addOutputSessionEffects(): failed to create Fx  music_helper on session 1337
11-01 15:27:50.660 1748-1929/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
11-01 15:27:50.662 1748-1929/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
11-01 15:27:50.664 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:50 +01:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:50.665 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:50 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 16
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:50.665 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:50 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:50.665 23837-23851/? I/Unity: 1 auth success:  False
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:50.680 23837-23851/? I/Unity:  [Play Games Plugin DLL] 11/01/18 15:27:50 +01:00 DEBUG: Invoking user callback on game thread
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-01 15:27:50.697 22786-22786/? I/AppLifecycleTracker: onActivityStopped: 
11-01 15:27:50.728 22786-22786/? I/AppLifecycleTracker: onActivityDestroyed:

**Comment by stabak** [comment]
> stabak, can you try Minimal sample if it works for you, please?

Hi @olehkuznetsov, minimal sample does not work either. It seems like I have 
"GamesNativeSDK: Play Games callback indicates connection failure."
in both attempts, followed by "ViewRootImpl[SignInActivity]: Attempting to destroy the window while drawing!". Please see the log for more.

To recap, I configured the project like so:

- create new project
- import Minimal package
- set package name
- create the google play console application
- create new game in game services
- link game with console application
- create achievement in game services game
- copy resources and paste into Google play games setup window in Unity 
- use constants class name "Minimal.GPGSIds" for minimal scene
- copy oauth2 client ID and paste into the field in the same window
- Build and run

Am I missing anything here?
Thanks for the answer,
[google play authenticate minimal scene logcat.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/2540044/google.play.authenticate.minimal.scene.logcat.txt)
