### ISSUE TITLE
"GooglePlayGamesManifest.plugin" is not loading in Unity 2021.2

### ISSUE THREAD

**Issue by HAL-JP** [playgameservices/play-games-plugin-for-unity#3088]
"GooglePlayGamesManifest.plugin" is not loading in Unity 2021.2.
Please see the following images first.

<img width="495" alt="スクリーンショット 2021-11-09 21 38 30" src="https://user-images.githubusercontent.com/81759313/140925771-2a0cd3d9-35b4-47cf-aa08-ac1135e3a3b5.png">
The above picture was exported in unity2021.1.

<img width="457" alt="スクリーンショット 2021-11-09 21 40 02" src="https://user-images.githubusercontent.com/81759313/140925860-25139716-a6a1-4b7d-8d80-685b6be414fa.png">
The above picture was exported in unity2021.2.

<img width="495" alt="スクリーンショット 2021-11-09 21 38 30" src="https://user-images.githubusercontent.com/81759313/140926135-7c4bfd29-830f-4f8d-a006-e75884195a7a.png">
As you can see by comparing the images, the GooglePlayGamesManifest.plugin is not present in unity2021.2. This needs to be fixed as soon as possible.

**Comment by ozdemir08** [comment]
Thanks for reporting this. I have looked into this issue and using Unity 2021.2 I got some errors too. 

It is likely that the issue is caused by `External Dependency Manager`. See [#447](https://github.com/googlesamples/unity-jar-resolver/issues/447) and [#440](https://github.com/googlesamples/unity-jar-resolver/issues/440). The issues there have been fixed and using its latest version fixed problems for me. 

We will make a release updating the EDM version. In the meantime, could you try out using the latest version of EDM and check if using the last version works for you? 

Only thing to do is after importing `Play Games Plugin for Unity`, to import [the latest version](https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage) of EDM into your project and clicking `Assets > External Dependency Manager > Android Resolver > Force Resolve`.

**Comment by HAL-JP** [comment]
Thank you for your reply.
I imported the latest External Dependency Manager version 1.2.167 into my project and ran `Assets > External Dependency Manager > Android Resolver > Force Resolve` to build. but it did not solve the problem.
However, I found a solution to the problem, which I will share with you. If you change the `.plugin` at the end of `GooglePlayGamesManifest.plugin` to `.androidlib` and add `GooglePlayGamesManifest.androidlib` to `Assets > Plugins > Android`, it will load.

**Comment by ozdemir08** [comment]
Using the latest `External Dependency Manager`, I was able to resolve dependencies and build the project. So, I could not reproduce the error. Could you write down each one of the reproduction steps? I see from the screenshots that you are using Android Studio. After importing the plugin into your Unity project, do you export it for Android Studio?

**Comment by franpereira** [comment]
> Thank you for your reply. I imported the latest `External Dependency Manager` version `1.2.167` into my project and ran `Assets > External Dependency Manager > Android Resolver > Force Resolve` to build. but it did not solve the problem. However, I found a solution to the problem, which I will share with you. If you change the `.plugin` at the end of `GooglePlayGamesManifest.plugin` to `.androidlib` and add `GooglePlayGamesManifest.androidlib` to `Assets > Plugins > Android`, it will load.

Thanks! Those steps worked for me too.

**Comment by Mejval5** [comment]
> Thank you for your reply. I imported the latest `External Dependency Manager` version `1.2.167` into my project and ran `Assets > External Dependency Manager > Android Resolver > Force Resolve` to build. but it did not solve the problem. However, I found a solution to the problem, which I will share with you. If you change the `.plugin` at the end of `GooglePlayGamesManifest.plugin` to `.androidlib` and add `GooglePlayGamesManifest.androidlib` to `Assets > Plugins > Android`, it will load.


Holy cow. This was a bitch to fix, thank you for the fix! This bug happens in Unity 2021.2.0f1. After two days on this issue I finally found this fix working. Thank you again

**Comment by ozdemir08** [comment]
Thank you all. We have fixed the bug internally as well, thanks to @HAL-JP and are planning to make a release in the next couple of days.

**Comment by ozdemir08** [comment]
We have made a new release including the fix. Let us know if you still face the same problem with the latest release. Thanks all for your contribution.

**Comment by toxikman** [comment]
Why was the .androidlib folder moved to /Assets/Plugins?  I'm 95% sure it is not necessary to move the .androidlib folder to /Assets/Plugins directory. 2021.2 did stop working for folders with .plugin extension so it was necessary to rename it to .androidlib.  These plugins can reside anywhere in the Assets folder. For project maintenance, we actually prefer the way it was before where all the Google Play Games related files are fully contained within the GooglePlayGames folder.
