### ISSUE TITLE
Can't login with 0.9.10 or 0.9.11 on Lollipop

### ISSUE THREAD

**Issue by seaders** [playgameservices/play-games-plugin-for-unity#372]
Using the Minimal sample, with the plugin installed, and set up correctly (appId, SHA1 set and linked), I can't get authentication to work, in any way.

Via logcat, during https://www.youtube.com/watch?v=2NwWgKPr-4M (I've edited out the email part, to preserve my email addresses, but be assured, I tap an email address that's in the testers section of my app),

	V/GamesNativeSDK(25127): Received Activity Resume Event.
	I/Unity(25127): onResume
	I/Unity(25127): windowFocusChanged: true
	I/Unity(25127):  [Play Games Plugin DLL] 01/21/15 3:56:24 +00:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus True
	I/Unity(25127): UnityEngine.Debug:Internal_Log(Int32, String, Object)
	I/Unity(25127): UnityEngine.Debug:Log(Object)
	I/Unity(25127): GooglePlayGames.OurUtils.Logger:d(String) (at /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/Logger.cs:46)
	I/Unity(25127): GooglePlayGames.OurUtils.PlayGamesHelperObject:OnApplicationFocus(Boolean) (at /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:102)
	I/Unity(25127):  
	I/Unity(25127): (Filename: /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 46)
	I/Unity(25127):  [Play Games Plugin DLL] 01/21/15 3:56:24 +00:00 DEBUG: PlayGamesHelperObject.OnApplicationPause False
	I/Unity(25127): UnityEngine.Debug:Internal_Log(Int32, String, Object)
	I/Unity(25127): UnityEngine.Debug:Log(Object)
	I/Unity(25127): GooglePlayGames.OurUtils.Logger:d(String) (at /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/Logger.cs:46)
	I/Unity(25127): GooglePlayGames.OurUtils.PlayGamesHelperObject:OnApplicationPause(Boolean) (at /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:109)
	I/Unity(25127):  
	I/Unity(25127): (Filename: /Developer/repos/git/NewUnityProject2/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 46)
	D/Unity(25127): Sensor :        Accelerometer ( 1) ; 0.000595 / 0.00s ; MPU6515 Accelerometer / InvenSense 
	V/GamesNativeSDK(25127): Play Games callback indicates connection failure.
	I/GamesNativeSDK(25127): UI interaction required to connect to Google Play.
	V/GamesNativeSDK(25127): Play Games callback indicates connection failure.
	I/GamesNativeSDK(25127): UI interaction required to connect to Google Play.
	V/GamesNativeSDK(25127): Play Games callback indicates connection failure.
	I/GamesNativeSDK(25127): UI interaction required to connect to Google Play.
	V/GamesNativeSDK(25127): Play Games callback indicates connection failure.
	I/GamesNativeSDK(25127): UI interaction required to connect to Google Play.
	I/Unity(25127):  [Play Games Plugin DLL] 01/21/15 3:56:27 +00:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
	I/Unity(25127):  
	I/Unity(25127): (Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
	I/Unity(25127):  [Play Games Plugin DLL] 01/21/15 3:56:27 +00:00 DEBUG: Invoking user callback on game thread

As I've said, I've tried both the latest 0.9.11 and (after reading some of the other threads experiencing this same issue) 0.9.10, no difference.  I've tried with all the config setup on initialise (on 0.9.11, it doesn't seem available as an option on 0.9.10), with debug on, or off, with the saveenabled on, and off.  With silent login enabled, and not, and no difference.

Any help at all with this issue?

**Comment by seaders** [comment]
I've just been able to test on a Galaxy S3 running 4.3 and everything works perfectly, so it's obviously some issue to do with Play Services and Lollipop (upgrading the play services lib to newest 6587000 also makes no difference).

**Comment by abbail** [comment]
I have the same exact problem.  My logcat even looks the same.  Doesn't work on Android 4.4.4 any way I try it.

**Comment by erikblue88** [comment]
Hi, I have a similar problem but my build is for iOS, in xcode i can see this error: 

[Play Games Plugin DLL] 03/24/15 9:38:04 -06:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_INTERNAL

In my developer console my email is in the testers and i have configured an ios application with the correct bundle id, but not the itunes id and it say ready for testing.

Anybody has an idea?

Thanks.

**Comment by erikblue88** [comment]
Ok, I finally found a solution that is the mentioned in #340.
I have activated the saved games in the developer console and now i can login succesfully.

Regards!

**Comment by claywilkinson** [comment]
Great News @erikblue88 ! Thanks.

**Comment by NaxIonz** [comment]
@erikblue88 
I noticed that you followed that you simply needed to turn on "Saved Games" on the console and that worked for you? I ask because we are now setting up our 2nd app, and it just is *NOT* working. We get "SIGN_IN status: ERROR_NOT_AUTHORIZED" for everyone.

@claywilkinson 
Why did you close this? The original author, @seaders , never said that they got things working. And now that we are experiencing the same agony all over again with our 2nd App has me wondering how else you can be getting the : "SIGN_IN status: ERROR_NOT_AUTHORIZED"

Clay, can you please list all the possible reasons that one could receive that error? This is a bit frustrating to implement when there is very little debug information to go off of or to understand why this is such a fragile process to get working.

**Comment by erikblue88** [comment]
@NaxIonz 
In my attempt to solve this problem I ran into that versions 0.9.10 and 0.9.11 have still some issues regarding the saved games.

I activated that option in the console and the error was fixed.

The code I'm using to activate play services is as follows:

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
// enables saving game progress.
            .EnableSavedGames()
            .Build();
        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();

Hope this help.

**Comment by NaxIonz** [comment]
@erikblue88 
Thanks - We are using the exact same Unity code to access GPGS in our new app that we were in our old app. And, once again, I have painstakingly checked bundle ID's and App ID's for the last two days. "Save Games" is enabled on our new app dashboard. The list of testers is exactly the same. The only thing that I can possibly think of is that new GPGS game is not "Published,"  but that is because it's still in development. So, unless this plugin relies on being "Published" then I have run out of ideas as to why we cannot get the new app to work (but were able to get the previous one working.... eventually).

**Comment by erikblue88** [comment]
@NaxIonz 
That is very strange, if everything is properly configured, I can not think what else could be wrong.
No need to be published, I have not published my app and still can test.
In the moment the app ask you for permission, It ask you for permission to acces google drive?
Otherwise, the saved games are not configured correctly and that could be the problem.

**Comment by seaders** [comment]
So from my point of view, I was on Android 5.0 on a Nexus 5, and now that I upgraded to 5.0.1 this error has disappeared.  I don't have another testing device to test on 5.0, so it could well still exist there, but on latest Android, I seem to be good, but I do agree with Naxlonz that this shouldn't have been closed without confirmation from me that the problem was sorted.

And in general, there just has to be better logging to help debug these issues.  From my point of view, I think I may have been suffering from that Android bug where the app would report the incorrect key signature for some apps signed by 128-bit keys that hit Lollipop.  *I think*.

**Comment by NaxIonz** [comment]
@erikblue88 
We are using the same test devices we used on our last app that we got Google Play Games to work on. We are also using the same client code to log in and authenticate.

I've re-run the "Android Setup" inside Unity about 6 times now, to no avail. AndroidManifest.xml, GameInfo.cs, and projsettings.txt all have the new app's App ID correctly in it. I've combed that 12-digit number for three days now.

The extra frustrating thing is that it works iOS. Yes, this 2nd game we are adding is both on Android and iOS (the previous game was just Android). So, the dashboard must be setup correctly if iOS is working, but for all the effort I can muster, Android simply won't authenticate. I see the GPGS UI come up, I see our game's icon, and yet I constantly get  "SIGN_IN status: ERROR_NOT_AUTHORIZED"

@claywilkinson 
Can we please get some clarity/insight on this situation?

**Comment by seaders** [comment]
What are the Android versions of the test devices you're using?  And just because it works on iOS, that has nothing to do with how things are set up on Android.

A few pointers, to make 100% sure all's good in your setup.  After compiling the Android APK, unzip it with any good zip tool, and run "keytool -printcert -file META-INF/CERT.RSA" in that directory.  Ensure that the SHA1 signature there is the same as what's set up in the Google Developer Console.

Also, I've found that setting up thing in the Developer Console (https://console.developers.google.com/project) first can break things a bit.  Delete the Client ID for Android from Google Developer Console, and instead link the api project from there to the Game Service area of your game (https://play.google.com/apps/publish) in "Linked Apps".  I've read more than a few places doing that the wrong way around can break authentication.

**Comment by NaxIonz** [comment]
@seaders 
I just checked and the SHA1 on the Developer Console is different than the build I just made.
How do I get those two to match? (I don't recall doing this on our last game)

**Comment by seaders** [comment]
You should be able to just straight up edit that field in the Google Developer console (https://console.developers.google.com/project), but realistically, if that's wrong there, I'd 100% recommend you delete that Client ID, and run through the set up in the Google Play console (https://play.google.com/apps/publish).

If you've already uploaded an APK to the game area there, go to Game Services, and either enter into, or create your Game Service area of your game there.  Then, when in there, go to "Linked Apps" and link a new app there.  If there was already one there, delete it and run through this again, it only takes a moment.  When you're going through that process, it'll pop up with a window displaying the SHA1 that was used to sign the APK that was uploaded there.

If *that* SHA1 doesn't match the one from the APK you have, then you've a horrible-ish situation with key signing that either you're signing with a different key than the original one, or someone else in your team signed that APK and uploaded it.  One way or another, that's a kind of a different problem.  You'll have to then start using that key to sign your APKs from now on.

On the main section of the Game Service area of your game, link the API project there too.

As for you not doing this before on your last game, depending on when you set that up, the consoles change (and a helluva lot of times, not for the better, same with iOS).

**Comment by NaxIonz** [comment]
@seaders 
You, sir, are my hero. It took a while, but we deleted the project on the Google Developer Console, and then remade it on the Google Play Console. Previous, it seems we had done it in the opposite order. Why the order of creation matters, is beyond me and absolutely asinine, but thanks to you, that was the issue!

It wasn't a code issue. It wasn't a tester issue. It wasn't an issue with any option on the Play Console. None of that, simply creating one one Google console before other Google console. Such a fragile and deplorable setup they have.

**Comment by seaders** [comment]
I wouldn't necessarily go that far, because at the end of the day, with the API access Google have built, and have on offer, it's damn complicated stuff, and while I think their docs could be better, the steps I mentioned are in more than a few places over the web.

Realistically, this is just a case of kinda bleeding edge.  If you think this is bad, jump in to some server-side web-dev and management.  Writing a meta ruby file to define which version of library x and y should be installed on some machine.... kills me a little inside when it doesn't work with any of the 20 official methods I've read online...

**Comment by samtstern** [comment]
@NaxIonz / @seaders 
I can confirm that it does, in many cases, matter that you configure all Play Game Services project through the Play console rather than the Google Developer Console.  This is due to some extra information that is associated with your game project that GDC doesn't know to configure. 

As far as getting different SHA1 signatures, I have had this issue before and it resulted from multiple `debug.keystore`
