### ISSUE TITLE
[0.9.12] crash in achievements ui

### ISSUE THREAD

**Issue by domino1011** [playgameservices/play-games-plugin-for-unity#411]
I was not able to show it twice, sometimes it crashes with the first call. My application still works fine after that (while the crash popup is shown and I can report it) while no play-games features are available. And when launching application again after the crash it takes like at least 30 seconds to even show a unity banner (this takes no time normally). 

Exception from the achievements ui:
```
E/AndroidRuntime(32327): FATAL EXCEPTION: main
E/AndroidRuntime(32327): Process: com.google.android.gms.ui, PID: 32327
E/AndroidRuntime(32327): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.getLocationInWindow(int[])' on a null object reference
E/AndroidRuntime(32327): 	at com.google.android.play.a.a.a(SourceFile:128)
E/AndroidRuntime(32327): 	at com.google.android.gms.games.ui.cp.run(SourceFile:45)
E/AndroidRuntime(32327): 	at com.google.android.gms.games.ui.co.a(SourceFile:51)
E/AndroidRuntime(32327): 	at android.support.v7.widget.br.run(SourceFile:248)
E/AndroidRuntime(32327): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
E/AndroidRuntime(32327): 	at android.view.Choreographer.doCallbacks(Choreographer.java:596)
E/AndroidRuntime(32327): 	at android.view.Choreographer.doFrame(Choreographer.java:556)
E/AndroidRuntime(32327): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
E/AndroidRuntime(32327): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(32327): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32327): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime(32327): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime(32327): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32327): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32327): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime(32327): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/ActivityManager(  891): App crashed! Process: com.google.android.gms.ui
W/ActivityManager(  891):   Force finishing activity com.google.android.gms/.games.ui.client.achievements.ClientAchievementListActivity 
```

also I noticed following exception just before signin in in gps:
```
Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.darkmountainstudio.vr.test/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]].
```

**Comment by spotavi** [comment]
Unity 4.6.2 has fixes for try catch issues related to some exception. See if building with 4.6.2 fixes the issues.

**Comment by PaoloMonkey** [comment]
I have this exact same issue too, game built with 4.6.2

**Comment by claywilkinson** [comment]
This appears to be a bug on the Google side - stay tuned for a fix...

**Comment by PaoloMonkey** [comment]
Still present with 4.6.3

**Comment by claywilkinson** [comment]
This was a bug in the games library on android. - it should be fixed now.  Can you confirm?

**Comment by PaoloMonkey** [comment]
No more crashes, everything's fine! =b (and no need to rebuild the game, which is kind of magic)

**Comment by claywilkinson** [comment]
Thanks for the quick update!

**Comment by christerwpersson** [comment]
Just thought I would let you know that the game doesn't crash, and everything works as intended. But the message does still appear in Unity 5

**Comment by claywilkinson** [comment]
@christerwpersson which message is appearing?

**Comment by christerwpersson** [comment]
```
Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.darkmountainstudio.vr.test/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]].
```

**Comment by christerwpersson** [comment]
@claywilkinson the message appears on every app start, and is preceded by
```
05-08 21:01:39.342: D/GamesUnitySDK(10850): Performing Android initialization of the GPG SDK
```

**Comment by claywilkinson** [comment]
Ahh - OK - that should be fixed in the latest plugin (0.9.20) - It is a harmless warning, but definitely annoying.
