### ISSUE TITLE
[crush] java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.

### ISSUE THREAD

**Issue by doterax** [playgameservices/play-games-plugin-for-unity#489]
Devices when I reproduce this bug:

* Nexus 5, Android 5.1
* Acer B1-730HD, Android 4.4.2
	
Steps to reproduce:

1. You must have device with two or more playgames accounts
2. When GPGS provide screen for choose wich one you want use
3. Press power button to lock the screen
4. Press power button to unlock the screen
 * (optional) enter password to unlock the screen
5. Choose any account and login
6. In my case, application crush with exception described below.

```
 java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
    at com.google.android.gms.common.internal.zzk.zzfc(Unknown Source)
    at com.google.android.gms.common.internal.zzk.zzjb(Unknown Source)
    at com.google.android.gms.games.internal.GamesClientImpl.zzno(Unknown Source)
    at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
    at com.google.android.gms.common.internal.zzl.zzj(Unknown Source)
    at com.google.android.gms.common.internal.zzl.zzfe(Unknown Source)
    at com.google.android.gms.common.internal.zzk$zzf.zzje(Unknown Source)
    at com.google.android.gms.common.internal.zzk$zza.zzc(Unknown Source)
    at com.google.android.gms.common.internal.zzk$zza.zzi(Unknown Source)
    at com.google.android.gms.common.internal.zzk$zzc.zzjg(Unknown Source)
    at com.google.android.gms.common.internal.zzk$zzb.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by claywilkinson** [comment]
Thanks for the bug report!

**Comment by doterax** [comment]
I found this article, may be helpfull http://www.codeitive.com/0yJqqWkegW/illegalstateexception-in-google-play-game-service-doesnt-make-sense.html

**Comment by ickimceo** [comment]
Here is another reports from my app.

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.4p3
Device model : LGE LG-D851
Device fingerprint: lge/g3_tmo_us/g3:4.4.2/KVT49L.D85110r/D85110r.1415271361:user/release-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5118)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
at dalvik.system.NativeStart.main(Native Method)

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.4p3
Device model : HUAWEI HUAWEI Y511-U30
Device fingerprint: HUAWEI/Y511-U30/HWY511-U:4.2.2/HUAWEIY511-U30/C328B118:user/release-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.4p3
Device model : samsung GT-I9300
Device fingerprint: samsung/m0xx/m0:4.3/JSS15J/I9300XXUGNB6:user/release-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at dalvik.system.NativeStart.main(Native Method)

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.4p3
Device model : samsung GT-I9505
Device fingerprint: samsung/jfltexx/jflte:4.4.2/KOT49H/I9505XXUGNJ3:user/release-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5356)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.4p3
Device model : alps V708-S
Device fingerprint: MT6572_JB3:4.2.2/HONGXIANG/M733W:user/test-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

**Comment by claywilkinson** [comment]
Thanks for the details.  There should be a fix shortly.

**Comment by doterax** [comment]
Do you have any estimates for this issue?

**Comment by claywilkinson** [comment]
I believe it should be fixed now.  Can you confirm it no longer happens?  If it does, can you let me know which  version of Google Play Services you are running and provide another log?

**Comment by doterax** [comment]
After update I can`t reproduse this bug. Choose screen automatically closes with cancel event. Possible fixed in v0.9.20

**Comment by doterax** [comment]
Bug is **not** fixed:
```
06-12 11:43:06.815: E/AndroidRuntime(29564): FATAL EXCEPTION: main
06-12 11:43:06.815: E/AndroidRuntime(29564): Process: com.candygrill.aquapolisgame, PID: 29564
06-12 11:43:06.815: E/AndroidRuntime(29564): java.lang.Error: FATAL EXCEPTION main
06-12 11:43:06.815: E/AndroidRuntime(29564): Unity version : 4.6.3f1
06-12 11:43:06.815: E/AndroidRuntime(29564): Device model : LGE Nexus 5
06-12 11:43:06.815: E/AndroidRuntime(29564): Device fingerprint: google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys
06-12 11:43:06.815: E/AndroidRuntime(29564): Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk.zzfc(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk.zzjb(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.games.internal.GamesClientImpl.zzno(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzl.zzj(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzl.zzfe(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk$zzf.zzje(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk$zza.zzc(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk$zza.zzi(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk$zzc.zzjg(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.google.android.gms.common.internal.zzk$zzb.handleMessage(Unknown Source)
06-12 11:43:06.815: E/AndroidRuntime(29564): at android.os.Handler.dispatchMessage(Handler.java:102)
06-12 11:43:06.815: E/AndroidRuntime(29564): at android.os.Looper.loop(Looper.java:135)
06-12 11:43:06.815: E/AndroidRuntime(29564): at android.app.ActivityThread.main(ActivityThread.java:5254)
06-12 11:43:06.815: E/AndroidRuntime(29564): at java.lang.reflect.Method.invoke(Native Method)
06-12 11:43:06.815: E/AndroidRuntime(29564): at java.lang.reflect.Method.invoke(Method.java:372)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
06-12 11:43:06.815: E/AndroidRuntime(29564): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by doterax** [comment]
How to reproduse:

1. Device with two or more google accounts
2. [Download](https://www.dropbox.com/s/4ail1ew2dn1y1fb/AquapolisGenericARMv7.apk?dl=0) and install build (APK)
3. When you see connect to GPGS screen during load - choose cancel.
4. After game tutorial (on 2 level) go into settings
5. Choose second tab and tap to Login to GPGS button
6. When you see connect screen - lock the device
7. Unlock the device 
8. Choose account and connect

After this you should see crush.

**Comment by claywilkinson** [comment]
Are you building your app with the latest cplay services client libary?  You can check that in your SDK manager.  Can you also  check what version of play services you are running? Also what version of Play Games is installed?

**Comment by ickimceo** [comment]
Sorry... It is not fixed with google_play_services_version: 7327000(rev. 24)

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.6.5p4
Device model : samsung GT-I9295
Device fingerprint: samsung/jactiveltevj/jactivelte:5.0.1/LRX22C/I9295VJUDOC3:user/release-keys

Caused by: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5942)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by claywilkinson** [comment]
Can you update Google play services?  It was fixed in 7.5+

**Comment by doterax** [comment]
Sorry but what i need to update? Application on smartphone. Or some part of
android SDK?

чт, 11 Июн 2015, 1:45, Clayton Wilkinson <notifications@github.com>:

**Comment by claywilkinson** [comment]
No problem :)  You need to update Google Play Services on your phone.  To do this, open the app list and find Google Settings (It is a grey gear icon), and then drag it to the top of the screen to the info, or App info icon.  This will open the information for the app, and the Update button should be enabled.

**Comment by doterax** [comment]
Thank you for explanation.
I have Google play servises v7.5.73.
Android 5.1.1 on Nexus 5

Bug still happens.

чт, 11 Июн 2015, 4:53, Clayton Wilkinson <notifications@github.com>:

**Comment by claywilkinson** [comment]
Can you post a log of it happening with 7.5.73?  Since some of the callstack is obfuscated, it will help try to figure out what is going on in the internal packages.

**Comment by doterax** [comment]
I already post when reopen task.

чт, 11 Июн 2015, 17:49, Clayton Wilkinson <notifications@github.com>:

**Comment by claywilkinson** [comment]
OK - can you update your SDK to rev 25 in your game?  I am trying to reproduce it myself too.

**Comment by claywilkinson** [comment]
@doterax - I was able to downgrade my client library to rev 24 and I changed nothing on my phone.  Following your instructions I was able to reproduce the issue.  I then updated to rev 25 in SDK manager, ran Windows > Google Play Games > Setup > Android Setup again (to pick up the new SDK).  It ran OK after that.

Apologies for the confusion.  Please let me know if your experience is the same.

**Comment by doterax** [comment]
I try to update SDK то version 25. But this library conflicts with [libGoogleAnalyticsServices.jar](https://developers.google.com/analytics/devguides/collection/android/v3/)


```
Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:\Program Files (x86)\Java\jdk1.7.0_51\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:/adt-bundle-windows-x86_64-20140702/sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files (x86)/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command$1;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
```
:worried:

**Comment by claywilkinson** [comment]
I found this thread on Stackoverflow: http://stackoverflow.com/questions/29986206/unable-to-execute-dex-multiple-dex-files-define-lcom-google-android-gms-analyti

I'll try to re-create this one too.

**Comment by doterax** [comment]
Hi Clayton,

I update google-play-services.jar to v25 and just remove libGoogleAnalyticsServices.jar from Plugins/Android

Our QA says: "Analytics works fine. Bug stop reprodusing."

Thank you very much!

**Comment by claywilkinson** [comment]
Great news! Thanks for the update.

**Comment by prakashangappan** [comment]
Hi,

I am facing the same issue. Could you please explain how did you fix this?.

Everything was working fine, suddenly this issue coming after we released the game on google play.  :( 

1. How/Where to Update google-play-services.jar to v25
2. I couldn't find libGoogleAnalyticsServices.jar from Plugins/Android folder.

Using,

Unity4.6.2p2
Updated Android Sdk to 5.1.1 API 22
Google play plugin 0.9.11

Thanks in advance!

**Comment by doterax** [comment]
1. In Android SDK Manager find Extras\Google Play Servises. Revision should be 25 or greater.
2. After this in Unity select. Window\Google Play Games\Setup\Android setup...

This should help.

**Comment by prakashangappan** [comment]
Thanks for the quick reply.
1. Found it, its 25.
2. Couldn't find where it is exactly, any idea?. I am using macbook. Did you mean, It should be inside unity's folder structure or android sdk's folder structure in the mac. I checked in both anyways, I couldn't find this file. :(

**Comment by doterax** [comment]
2. Search in Unity editors menu
Вт, 14 июля 2015 г. в 12:29, prakashangappan <notifications@github.com>:
